### PR TITLE
Value rewrite rule

### LINKED ISSUE #16: Transform header values
The ability to transform header _values_ via regex, as requested [here](https://github.com/traefik/traefik/issues/6047#issue-538762623) for **ValueRewriteRule** - would be extremely useful.

### PR DESCRIPTION
**Pull request by ant1m**
Here you go.
I wondered if there is something to do about the regex matching duplication but couldn't find anything relevant.

Fixes #16

### CODE REVIEW

**Comment by Shotster** [comment]
Can the new header value be specified using a regex replacement on the existing value?

**Comment by adyanth** [comment]
This brings Regex Match to Set, right? Can this not be integrated in Set itself? Rather than a new Type?

**Comment by ant1m** [comment]
Bringing Regex Match to Set would be confusing, I guess, since Set can already update but create new headers as well. So I used the type mentioned in the traefik issue linked.
And no I didn't implement captures. You're right, I'll add it now.

**Comment by adyanth** [comment]
Ahh, makes sense. New headers with Regex would not work.

But then, #16 seems to talk about regex matching the values, not the header itself. Just making sure if that is what the issue was about.

**Comment by ant1m** [comment]
It's not quite clear. The traefik issue says "header is a parameter to match an header or a set of headers". I guessed the regex match is on the header name and change on the value of the matched header(s). I may have misinterpreted this. If it's clearer for you, could you provide a more detailed specification of what is expected ?

**Comment by Shotster** [comment]
> be able to transform e.g: `X-Test: Hello1231` to `X-Test: Hi1231` using regex like `(\d+)$` to `Hi$1`

Yes, this is exactly what I meant (and what I understood https://github.com/traefik/traefik/issues/6047#issue-538762623 to be requesting).

**Comment by ant1m** [comment]
I still don't understand how such a rule could match a set of headers, but I'll do this.

**Comment by adyanth** [comment]
I guess you are reading Header Rewrite Rule.
>HeaderRewriteRule(regex, replace)
>Rewrite header name using a regex with a match/capture.
>
>Example:
>
>HeaderRewriteRule(`MY_(.*)`, `NEW_$1`)
>Would change the following requests from:
>
>MY_HEADER: super
>MY_OTHER_HEADER: 123
>To:
>
>NEW_HEADER: super
>NEW_OTHER_HEADER: 123

>ValueRewriteRule(header, regex, replace)
>Same as the header rewrite but for their content, header is a parameter to match an header or a set of headers to apply the rewrite rule.

Here, the Header match is similar to Rename operation, where you can specify `X-Traefik-*` to match a bunch of similar headers. But the actual operation is applying the regex transform to the values of these matched headers. 

Overall similar to Rename while searching for headers to modify, but instead of changing the header names, we change the values. This needs 3 inputs, header (maybe regex like), value match regex, value replace with regex.

**Comment by ant1m** [comment]
That's much clearer, thanks.

**Comment by adyanth** [comment]
I guess this does all what the issue needed, awesome!

Does this handle the edge case for when there are no capture groups in the regex? (In which case, the replace value would be a normal string) E.g: `\d*` to `-numberhidden-`, so `abc123def` would become `abc-numberhidden-def` something like this?

**Comment by ant1m** [comment]
I added a few test cases to document the edge cases. 
I didn't handle the case where there is no capture group, because I thought it would make things confusing and lead to more edge cases about eager matching, multiple match, multiple substring candidates replacements, etc.

**Review by tomMoulard — APPROVED** [review]
LGTM :ok_hand:

**Pull request merged**
